### ISSUE TITLE
Some tokens don't get unique colours like original gruvbox

### ISSUE THREAD

**Issue by Integralist** [luisiacc/gruvbox-baby#21]
👋🏻 First off, amazing job on this colourscheme. I love it.

Just one issue I have is that there are some tokens that have the same colours as other tokens, which doesn't happen with the original gruvbox theme.

Below are two screenshots that demonstrate this. Both are of the same window/buffer layout (lua file + go file) but just with the two colourschemes (gruvbox and gruvbox-baby) being used.

You'll notice in the lua file the `augroup packer_use_config` has two separate colours with gruvbox, while they are the same red colour in gruvbox-baby.

Similarly, in the go file, you'll see on line 35 `BeforeSend: func(event *sentry.Event` where `func` and the word `sentry` are the same red colour with gruvbox-baby where as with gruvbox they are unique colours.

Just wanted to flag this in case it was a mistake, or if intended, would it be possible to make these unique colours, as the heavy overlapping of 'red' can be a bit distracting for me.

Either way. Great theme!

Thanks 🙂 

<img width="2032" alt="Screenshot 2022-08-05 at 09 52 51" src="https://user-images.githubusercontent.com/180050/183042526-ee7b2742-1dd7-47dc-8e4c-799baf921b3a.png">

<img width="2032" alt="Screenshot 2022-08-05 at 09 52 58" src="https://user-images.githubusercontent.com/180050/183042554-0079e71c-7ad0-4410-96a5-b85487b96921.png">

**Comment by luisiacc** [comment]
Yeah those definitely don't look good on red, I've addressed that here: https://github.com/luisiacc/gruvbox-baby/commit/f6e3418c8200f497f3b0c3ef35237d855fbbb995

**Comment by Integralist** [comment]
Thanks @luisiacc although I didn't call it out, is there a reason the URL on line 26 is partially red/green?

**Comment by Integralist** [comment]
Interestingly it looks to not be related to the string being inside a struct, but just a general string/URL parsing, because if I A.) change the URL I still see the issue, and B.) if I create a variable with the URL outside of the struct then it still happens...

<img width="408" alt="Screenshot 2022-08-08 at 10 25 22" src="https://user-images.githubusercontent.com/180050/183385766-09c664cc-3a06-4651-b45c-ee10732b5093.png">

**Comment by luisiacc** [comment]
> Thanks @luisiacc although I didn't call it out, is there a reason the URL on line 26 is partially red/green

Hmm that's very weird, that has never happened to me, I have no idea what it could be.

**Comment by Integralist** [comment]
Ah well I guess if you don't see that happening it's likely Zellij or Alacritty doing something odd. 

I'll validate this later when I'm on my laptop. 

Thanks again.

**Comment by Integralist** [comment]
Just to confirm for any future travellers, this wasn't Alacritty, it was Zellij.
